/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerBookIdRouteImport } from './routes/player/$bookId'
import { Route as LabLocateIndexRouteImport } from './routes/lab.locate.index'
import { Route as LabLocateBookIdRouteImport } from './routes/lab.locate.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerBookIdRoute = PlayerBookIdRouteImport.update({
  id: '/player/$bookId',
  path: '/player/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLocateIndexRoute = LabLocateIndexRouteImport.update({
  id: '/lab/locate/',
  path: '/lab/locate/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLocateBookIdRoute = LabLocateBookIdRouteImport.update({
  id: '/lab/locate/$bookId',
  path: '/lab/locate/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/locate/': typeof LabLocateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/locate': typeof LabLocateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/locate/': typeof LabLocateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/player/$bookId' | '/lab/locate/$bookId' | '/lab/locate/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player/$bookId' | '/lab/locate/$bookId' | '/lab/locate'
  id:
    | '__root__'
    | '/'
    | '/player/$bookId'
    | '/lab/locate/$bookId'
    | '/lab/locate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerBookIdRoute: typeof PlayerBookIdRoute
  LabLocateBookIdRoute: typeof LabLocateBookIdRoute
  LabLocateIndexRoute: typeof LabLocateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$bookId': {
      id: '/player/$bookId'
      path: '/player/$bookId'
      fullPath: '/player/$bookId'
      preLoaderRoute: typeof PlayerBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/locate/': {
      id: '/lab/locate/'
      path: '/lab/locate'
      fullPath: '/lab/locate/'
      preLoaderRoute: typeof LabLocateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/locate/$bookId': {
      id: '/lab/locate/$bookId'
      path: '/lab/locate/$bookId'
      fullPath: '/lab/locate/$bookId'
      preLoaderRoute: typeof LabLocateBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerBookIdRoute: PlayerBookIdRoute,
  LabLocateBookIdRoute: LabLocateBookIdRoute,
  LabLocateIndexRoute: LabLocateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
