/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteImport } from './routes/lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as PlayerBookIdRouteImport } from './routes/player/$bookId'
import { Route as LabVttIndexRouteImport } from './routes/lab.vtt.index'
import { Route as LabLocateIndexRouteImport } from './routes/lab.locate.index'
import { Route as LabEpubIndexRouteImport } from './routes/lab.epub.index'
import { Route as LabCorporaIndexRouteImport } from './routes/lab.corpora.index'
import { Route as LabAudiobooksIndexRouteImport } from './routes/lab.audiobooks.index'
import { Route as LabAlignmentIndexRouteImport } from './routes/lab.alignment.index'
import { Route as LabLocateBookIdRouteImport } from './routes/lab.locate.$bookId'

const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LabRoute,
} as any)
const PlayerBookIdRoute = PlayerBookIdRouteImport.update({
  id: '/player/$bookId',
  path: '/player/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabVttIndexRoute = LabVttIndexRouteImport.update({
  id: '/vtt/',
  path: '/vtt/',
  getParentRoute: () => LabRoute,
} as any)
const LabLocateIndexRoute = LabLocateIndexRouteImport.update({
  id: '/locate/',
  path: '/locate/',
  getParentRoute: () => LabRoute,
} as any)
const LabEpubIndexRoute = LabEpubIndexRouteImport.update({
  id: '/epub/',
  path: '/epub/',
  getParentRoute: () => LabRoute,
} as any)
const LabCorporaIndexRoute = LabCorporaIndexRouteImport.update({
  id: '/corpora/',
  path: '/corpora/',
  getParentRoute: () => LabRoute,
} as any)
const LabAudiobooksIndexRoute = LabAudiobooksIndexRouteImport.update({
  id: '/audiobooks/',
  path: '/audiobooks/',
  getParentRoute: () => LabRoute,
} as any)
const LabAlignmentIndexRoute = LabAlignmentIndexRouteImport.update({
  id: '/alignment/',
  path: '/alignment/',
  getParentRoute: () => LabRoute,
} as any)
const LabLocateBookIdRoute = LabLocateBookIdRouteImport.update({
  id: '/locate/$bookId',
  path: '/locate/$bookId',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab/': typeof LabIndexRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/alignment/': typeof LabAlignmentIndexRoute
  '/lab/audiobooks/': typeof LabAudiobooksIndexRoute
  '/lab/corpora/': typeof LabCorporaIndexRoute
  '/lab/epub/': typeof LabEpubIndexRoute
  '/lab/locate/': typeof LabLocateIndexRoute
  '/lab/vtt/': typeof LabVttIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab': typeof LabIndexRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/alignment': typeof LabAlignmentIndexRoute
  '/lab/audiobooks': typeof LabAudiobooksIndexRoute
  '/lab/corpora': typeof LabCorporaIndexRoute
  '/lab/epub': typeof LabEpubIndexRoute
  '/lab/locate': typeof LabLocateIndexRoute
  '/lab/vtt': typeof LabVttIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRouteWithChildren
  '/player/$bookId': typeof PlayerBookIdRoute
  '/lab/': typeof LabIndexRoute
  '/lab/locate/$bookId': typeof LabLocateBookIdRoute
  '/lab/alignment/': typeof LabAlignmentIndexRoute
  '/lab/audiobooks/': typeof LabAudiobooksIndexRoute
  '/lab/corpora/': typeof LabCorporaIndexRoute
  '/lab/epub/': typeof LabEpubIndexRoute
  '/lab/locate/': typeof LabLocateIndexRoute
  '/lab/vtt/': typeof LabVttIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/player/$bookId'
    | '/lab/'
    | '/lab/locate/$bookId'
    | '/lab/alignment/'
    | '/lab/audiobooks/'
    | '/lab/corpora/'
    | '/lab/epub/'
    | '/lab/locate/'
    | '/lab/vtt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player/$bookId'
    | '/lab'
    | '/lab/locate/$bookId'
    | '/lab/alignment'
    | '/lab/audiobooks'
    | '/lab/corpora'
    | '/lab/epub'
    | '/lab/locate'
    | '/lab/vtt'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/player/$bookId'
    | '/lab/'
    | '/lab/locate/$bookId'
    | '/lab/alignment/'
    | '/lab/audiobooks/'
    | '/lab/corpora/'
    | '/lab/epub/'
    | '/lab/locate/'
    | '/lab/vtt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  PlayerBookIdRoute: typeof PlayerBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/player/$bookId': {
      id: '/player/$bookId'
      path: '/player/$bookId'
      fullPath: '/player/$bookId'
      preLoaderRoute: typeof PlayerBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/vtt/': {
      id: '/lab/vtt/'
      path: '/vtt'
      fullPath: '/lab/vtt/'
      preLoaderRoute: typeof LabVttIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/locate/': {
      id: '/lab/locate/'
      path: '/locate'
      fullPath: '/lab/locate/'
      preLoaderRoute: typeof LabLocateIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/epub/': {
      id: '/lab/epub/'
      path: '/epub'
      fullPath: '/lab/epub/'
      preLoaderRoute: typeof LabEpubIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/corpora/': {
      id: '/lab/corpora/'
      path: '/corpora'
      fullPath: '/lab/corpora/'
      preLoaderRoute: typeof LabCorporaIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/audiobooks/': {
      id: '/lab/audiobooks/'
      path: '/audiobooks'
      fullPath: '/lab/audiobooks/'
      preLoaderRoute: typeof LabAudiobooksIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/alignment/': {
      id: '/lab/alignment/'
      path: '/alignment'
      fullPath: '/lab/alignment/'
      preLoaderRoute: typeof LabAlignmentIndexRouteImport
      parentRoute: typeof LabRoute
    }
    '/lab/locate/$bookId': {
      id: '/lab/locate/$bookId'
      path: '/locate/$bookId'
      fullPath: '/lab/locate/$bookId'
      preLoaderRoute: typeof LabLocateBookIdRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LabRouteChildren {
  LabIndexRoute: typeof LabIndexRoute
  LabLocateBookIdRoute: typeof LabLocateBookIdRoute
  LabAlignmentIndexRoute: typeof LabAlignmentIndexRoute
  LabAudiobooksIndexRoute: typeof LabAudiobooksIndexRoute
  LabCorporaIndexRoute: typeof LabCorporaIndexRoute
  LabEpubIndexRoute: typeof LabEpubIndexRoute
  LabLocateIndexRoute: typeof LabLocateIndexRoute
  LabVttIndexRoute: typeof LabVttIndexRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabIndexRoute: LabIndexRoute,
  LabLocateBookIdRoute: LabLocateBookIdRoute,
  LabAlignmentIndexRoute: LabAlignmentIndexRoute,
  LabAudiobooksIndexRoute: LabAudiobooksIndexRoute,
  LabCorporaIndexRoute: LabCorporaIndexRoute,
  LabEpubIndexRoute: LabEpubIndexRoute,
  LabLocateIndexRoute: LabLocateIndexRoute,
  LabVttIndexRoute: LabVttIndexRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  PlayerBookIdRoute: PlayerBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
